# Generated by Django 2.0.8 on 2019-11-24 22:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('zillow_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('home_size', models.PositiveIntegerField(blank=True)),
                ('zestimate_amount', models.PositiveIntegerField(blank=True)),
                ('rentzestimate_amount', models.PositiveIntegerField(blank=True)),
                ('last_sold_price', models.PositiveIntegerField(blank=True)),
                ('rent_price', models.PositiveIntegerField(blank=True)),
                ('property_size', models.PositiveIntegerField(blank=True)),
                ('tax_value', models.PositiveIntegerField(blank=True)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('rentzestimate_last_updated', models.DateField(blank=True)),
                ('last_sold_date', models.DateField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('area_unit', models.CharField(choices=[('SqFt', 'Square Foot'), ('SqM', 'Square Meter')], max_length=20)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Single Family'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Muliple Family (2 to 4)'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex')], max_length=30)),
                ('price', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\$(\\d*\\.?\\d{0,2})[KM]$', 'Your string should be in the format: $###.##M or $###K')])),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=20)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.RegexValidator('\\d*(\\.5)?$', 'You can only have whole and half baths.')])),
                ('tax_year', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800)])),
                ('year_built', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800)])),
            ],
        ),
    ]
