# Generated by Django 2.0.8 on 2019-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='zestimate_last_updated',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
