# Generated by Django 2.0.8 on 2019-11-25 00:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20191125_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
