# Generated by Django 2.0.8 on 2019-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20191125_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
