# Generated by Django 2.0.8 on 2019-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20191125_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
