# Generated by Django 2.0.8 on 2019-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_auto_20191125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
