# Generated by Django 2.0.8 on 2019-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20191125_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='property_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
