# Generated by Django 2.0.8 on 2019-11-25 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_auto_20191125_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.RegexValidator('\\d*(\\.5)?$', 'You can only have whole and half baths.')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='home',
            name='tax_year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800)]),
        ),
    ]
